# Mini-Project 1: Machine Learning 101

Christian Martel (260867191)

Luka Loignon (260871296)

Marie Guertin (260870552)

## Data Preprocessing

Acquire data, analyze it and clean it

### Adult Dataset

Prediction task is to determine whether someone makes over 50K a year.
https://archive.ics.uci.edu/ml/datasets/Adult

### X Dataset

// TODO: choose a dataset from https://archive.ics.uci.edu/ml/datasets.php 
// choose a dataset not too small not too large


1. Download datasets

2. Load datasets into Pandas dataframes or Numpy objects

3. Clean up the data : remove instances that have too many missing or invalid data entries.

4. Convert discrete variables into multiple using one-hot encoding (see Encoding categorical features in scikit learn doc)



In [1]:
import pandas as pd
import numpy as np
from pandas.api.types import is_string_dtype
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
# 13 feature columns and 2 prediction columns
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'salary']
categorical_columns = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

# import data to dataframes
train_df = pd.read_csv("data/adult.data", usecols = range(15), names = columns)
test_df = pd.read_csv("data/adult.test", usecols = range(15), names = columns)

# 1) CLEAN-UP
train_df_obj = train_df.select_dtypes(['object'])
test_df_obj = test_df.select_dtypes(['object'])

train_df[train_df_obj.columns] = train_df_obj.apply(lambda x: x.str.strip())
test_df[test_df_obj.columns] = test_df_obj.apply(lambda x: x.str.strip())


# 2) REMOVE USELESS FEATURES
# count number of zeros or nan values per column and drop columns with more than 75% of 0 or nan values
num_instances = train_df.shape[0]
useless_data_threshold = 0.75

for c in columns:
    useless_proportion = (train_df[c].isna().sum() + (train_df[c] == 0).sum()) / num_instances
    if useless_proportion > useless_data_threshold:
        train_df.drop(columns = c, inplace = True)
        test_df.drop(columns = c, inplace = True)

# 3) FEATURE ONE_HOT_ENCODING 

for cat in categorical_columns:    
    # concatenante one hot encoded dummies columns
    train_df, test_df = pd.concat([train_df, pd.get_dummies(train_df[cat], prefix = cat, prefix_sep = '_')], axis = 1), pd.concat([test_df, pd.get_dummies(train_df[cat], prefix = cat, prefix_sep = '_')], axis = 1)
    
    # drop old columns
    train_df, test_df = train_df.drop(columns = cat), test_df.drop(columns = cat)
    
# 4) MOVE PREDICTION COLUMN TO THE END

y_train, y_test = train_df.pop('salary'), test_df.pop('salary')
train_df, test_df = pd.concat([train_df, y_train],axis=1), pd.concat([test_df, y_test],axis=1)


# 5) NUMERIZE PREDICTION VARIABLE

# - '>50K': 1
# - '<=50K': 0
train_df['salary'] = train_df['salary'].apply(lambda x: 1 if (x == '>50K') else 0)
train_df

age  fnlwgt  education-num  hours-per-week  workclass_?  \
0       39   77516             13              40            0   
1       50   83311             13              13            0   
2       38  215646              9              40            0   
3       53  234721              7              40            0   
4       28  338409             13              40            0   
...    ...     ...            ...             ...          ...   
32556   27  257302             12              38            0   
32557   40  154374              9              40            0   
32558   58  151910              9              40            0   
32559   22  201490              9              20            0   
32560   52  287927              9              40            0   

       workclass_Federal-gov  workclass_Local-gov  workclass_Never-worked  \
0                          0                    0                       0   
1                          0                    0                       0   
2                          0                    0                       0   
3                          0                    0                       0   
4                          0                    0                       0   
...                      ...                  ...                     ...   
32556                      0                    0                       0   
32557                      0                    0                       0   
32558                      0                    0                       0   
32559                      0                    0                       0   
32560                      0                    0                       0   

       workclass_Private  workclass_Self-emp-inc  workclass_Self-emp-not-inc  \
0                      0                       0                           0   
1                      0                       0                           1   
2                      1                       0                           0   
3                      1                       0                           0   
4                      1                       0                           0   
...                  ...                     ...                         ...   
32556                  1                       0                           0   
32557                  1                       0                           0   
32558                  1                       0                           0   
32559                  1                       0                           0   
32560                  0                       1                           0   

       workclass_State-gov  workclass_Without-pay  education_10th  \
0                        1                      0               0   
1                        0                      0               0   
2                        0                      0               0   
3                        0                      0               0   
4                        0                      0               0   
...                    ...                    ...             ...   
32556                    0                      0               0   
32557                    0                      0               0   
32558                    0                      0               0   
32559                    0                      0               0   
32560                    0                      0               0   

       education_11th  education_12th  education_1st-4th  education_5th-6th  \
0                   0               0                  0                  0   
1                   0               0                  0                  0   
2                   0               0                  0                  0   
3                   1               0                  0                  0   
4                   0               0                  0                  0   
...               ...    

## Cross Validation

helper method to perform the splits for L-fold cross-validation

In [5]:
def cross_validate_splits(n, n_folds=5):
    # get the number of data samples in each split
    splits = []
    n_val = n // n_folds
    inds = np.random.permutation(n)
    inds = []
    for f in range(n_folds):
        tr_inds = []
        # get the validation indexes
        val_inds = list(range(f * n_val, (f+1) * n_val))
        
        # get the training indexes
        tr_inds = list()
        if f < n_folds - 1:
            tr_inds = list(range((f+1) * n_val, n))
        
        if f > 0:
            tr_inds = tr_inds + list(range(0, f * n_val))
        splits.append((tr_inds, val_inds))
    return splits

## Validation Metrics

In [6]:
# define MSE loss function
loss = lambda y, y_pred: np.mean((y-y_pred)**2)

#define accuracy function
accuracy = lambda y, y_pred: np.sum(y == y_pred)/y.size

## Experiment


In [8]:
from sklearn.neighbors import KNeighborsClassifier

# convert to numpy arrays
train, test = train_df.to_numpy(), test_df.to_numpy()

x, y = train[:, :-1], train[:, -1]
x_test, y_test = test[:, :-1], test[:, -1]

num_instances = train.shape[0]
K_list = list(range(1,3)) # [1,2]
L = 5

# l-fold cross validation splits
n_folds_splits = cross_validate_splits(num_instances, n_folds=L)


# find the best K hyper-parameter

# validation metrics (len(K_list) x L)
err_matrix = np.zeros((len(K_list),L))

# [[0 0 0 0 0],
#  [0 0 0 0 0]]

for i, K in enumerate(K_list):
    model = KNeighborsClassifier(n_neighbors=K)
    for j, split in enumerate(n_folds_splits):
        # split into train set and validation set
        x_train, x_val = x[split[0], :], x[split[1], :]
        y_train, y_val = y[split[0]], y[split[1]]

        model.fit(x_train, y_train)
        
        err_val = loss(y_val, model.predict(x_val))
        err_matrix[i][j] = err_val

err_matrix


array([[0.31296069, 0.31188575, 0.30697174, 0.31403563, 0.31464988],
       [0.25307125, 0.24769656, 0.24861794, 0.25644963, 0.25952088]])

## Visualization

- plot error vs KNN

## Titre
- a
- b

1. a
2. b

## Decision Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier

# convert to numpy arrays
train, test = train_df.to_numpy(), test_df.to_numpy()

x, y = train[:, :-1], train[:, -1]
x_test, y_test = test[:, :-1], test[:, -1]

num_instances = train.shape[0]
L = 5

# Decision Tree Parameters
max_d =  list(range(1,5))
crit = "entropy"

# l-fold cross validation splits
n_folds_splits = cross_validate_splits(num_instances, n_folds=L)


# find the best max-depth hyper-parameter

# validation metrics
err_matrix = np.zeros((len(max_d),L))

for i, M in enumerate(max_d):
    model = DecisionTreeClassifier(criterion=crit, max_depth = max_d[i])
    for j, split in enumerate(n_folds_splits):
        # split into train set and validation set
        x_train, x_val = x[split[0], :], x[split[1], :]
        y_train, y_val = y[split[0]], y[split[1]]

        model.fit(x_train, y_train)
        
        err_val = loss(y_val, model.predict(x_val))
        err_matrix[i][j] = err_val

err_matrix

array([[0.24124693, 0.23694717, 0.23786855, 0.24232187, 0.24554668],
       [0.18673219, 0.18089681, 0.17705774, 0.17628993, 0.18212531],
       [0.18519656, 0.17936118, 0.17782555, 0.17460074, 0.18074324],
       [0.18366093, 0.1784398 , 0.17613636, 0.17444717, 0.17997543]])